yarnPath: .yarn/releases/yarn-3.2.1.cjs
nodeLinker: node-modules
packageExtensions:
  "@remix-run/dev@1.6.0":
    peerDependencies:
      react: ">=16.8"
      react-dom: ">=16.8"
  "@remix-run/node@1.6.0":
    peerDependencies:
      react: ">=16.8"
      react-dom: ">=16.8"
  "@remix-run/express@1.6.0":
    peerDependencies:
      react: ">=16.8"
      react-dom: ">=16.8"
  "@remix-run/serve@1.6.0":
    peerDependencies:
      react: ">=16.8"
      react-dom: ">=16.8"
